name: Linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_BEFORE_ALL: >
                  yum install -y wget &&
                  wget ftp://ftp.gnu.org/gnu/gsl/gsl-latest.tar.gz &&
                  tar -zxvf gsl-latest.tar.gz &&
                  cd gsl-* &&
                  ./configure &&
                  make &&
                  make install
          CIBW_BEFORE_BUILD: >
                  pip3 install --upgrade pip &&
                  pip3 install Cython &&
                  pip3 install -r requirements.txt
          CIBW_BUILD: "cp38-manylinux*"
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
          
      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Upload wheels
        shell: bash
        env:
                PYPI_UPLOAD: ${{ secrets.PYPI_UPLOAD }}
                PYPI_USR: ${{ secrets.PYPI_USR }}
                PYPI_PWD: ${{ secrets.PYPI_PWD }}
                TEST_PYPI_USR: ${{ secrets.TEST_PYPI_USR }}
                TEST_PYPI_PWD: ${{ secrets.TEST_PYPI_PWD }}
        run: |
                pip3 install --upgrade pip
                pip3 install twine
                chmod +x upload_wheels.sh
                ./upload_wheels.sh
