name: macOS arm64

on:
  push:
    branches-ignore:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Before build
        run: |
                brew install gsl
                brew info gsl
                brew install llvm
                brew info llvm
        shell: bash

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_BEFORE_BUILD: >
                  pip3 install --upgrade pip &&
                  pip3 install Cython &&
                  pip3 install -r requirements.txt
          CIBW_BUILD: "cp38-macosx_arm64 cp39-macosx_arm64 cp310-macosx_arm64 cp311-macosx_x86_64"
          CIBW_ARCHS_MACOS: "arm64"
          
      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Upload wheels
        shell: bash
        env:
                TEST_PYPI_USR: ${{ secrets.TEST_PYPI_USR }}
                TEST_PYPI_PWD: ${{ secrets.TEST_PYPI_PWD }}
        run: |
                pip3 install --upgrade pip
                pip3 install twine
                chmod +x upload_test_wheels.sh
                ./upload_test_wheels.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS_arm64_wheels
          path: ./wheelhouse/*.whl
          if-no-files-found: warn
