name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      generate-attestation:
        description: 'Generate SLSA build provenance attestation'
        required: true
        type: boolean
        default: false
      vcpkg-commit-id:
        description: 'Optional vcpkg commit ID to use for the build'
        required: false
        type: string
        default: '120deac3062162151622ca4860575a33844ba10b'
      vs-version:
        description: 'Optional Visual Studio version range (e.g., "[17.0,18.0)")'
        required: false
        type: string
        default: ''
      uv-version:
        description: 'Optional uv version'
        required: false
        type: string
        default: 'latest'
      numpy-version:
        description: 'Optional numpy version'
        required: false
        type: string
        default: ''

jobs:
  build:
    permissions:
      id-token: write # Required for OIDC token
      contents: read   # Required to read source code
      attestations: write # Required to write attestations

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', 'latest']

    env:
      # 👇 Force triplet for all vcpkg installs
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
      VCPKG_DISABLE_METRICS: 1
      AUTO_SEARCH_VCPKG_GSL: "true"

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: ${{ inputs.vs-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
        version: "${{ inputs.uv-version || 'latest' }}"
        
    - name: Install python & Create Virtual Environment
      if: matrix.python-version == 'latest'
      run: |
        uv python list
        uv python install
        uv venv

    - name: Create Virtual Environment
      if: matrix.python-version != 'latest'
      run: uv venv --python "${{ matrix.python-version }}"

    - name: Cache vcpkg dependencies
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/vcpkg
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}-${{ inputs.vcpkg-commit-id }}-${{ inputs.vs-version }}
        restore-keys: |
          vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}-${{ inputs.vcpkg-commit-id }}-

    - name: Install pinned vcpkg
      id: vcpkg_pinned
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ inputs.vcpkg-commit-id || '120deac3062162151622ca4860575a33844ba10b' }}
      continue-on-error: true

    - name: Install latest vcpkg (on failure)
      id: vcpkg_latest
      if: steps.vcpkg_pinned.outcome == 'failure'
      uses: lukka/run-vcpkg@v11

    - name: Verify vcpkg installation
      if: steps.vcpkg_latest.outcome == 'failure' && steps.vcpkg_pinned.outcome == 'failure'
      run: |
        echo "::error::Both pinned and latest vcpkg installations failed."
        exit 1

    - name: Setup GSL via vcpkg
      shell: pwsh
      run: |
        cd ${{ github.workspace }}/vcpkg
        ls
        .\vcpkg install


    - name: Install Python dependencies
      run: uv pip install cython wheel pytest setuptools numpy${{ inputs.numpy-version }}

    - name: Build fathon wheel
      # Use --no-build-isolation to make the env vars available to setup.py
      run: uv build --wheel --verbose --no-build-isolation

    - name: uv lock
      run: uv lock && uv export --format requirements-txt --output-file dist/requirements.txt

    - name: Generate artifact attestation
      if: github.event_name == 'workflow_dispatch' && inputs.generate-attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: "dist/*.whl"

    - name: Install fathon from wheel
      shell: pwsh
      run: |
        $wheelFile = Get-ChildItem -Path "dist/fathon-*.whl"
        if ($wheelFile.Count -ne 1) {
          Write-Host "Contents of dist/ directory:"
          Get-ChildItem -Path "dist/"
          throw "Error: Expected to find exactly one 'fathon-*.whl' file, but found $($wheelFile.Count)."
        }
        uv pip install "$wheelFile.FullName"

    - name: Run tests
      run: uv run pytest tests/

    - name: Upload Wheel Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fathon-wheel-${{ matrix.python-version }}
        path: dist/

    - name: Upload Vcpkg Packages Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gsl-libs-${{ matrix.python-version }}
        path: ${{ github.workspace }}/vcpkg/packages/
