name: Windows

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on windows-2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Before build
        run: |
          cd C:\Tools\vcpkg
          git pull
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg.exe install gsl:x64-windows-static
          "python3 -m pip install --upgrade pip"
        shell: ps

      #- name: Build wheels
      #  uses: pypa/cibuildwheel@v2.5.0
      #  env:
      #    CIBW_BUILD_VERBOSITY: 1
      #    CIBW_TEST_REQUIRES: pytest
      #    CIBW_TEST_COMMAND: "pytest {project}/tests"
      #    CIBW_BEFORE_BUILD: >
      #            pip3 install --upgrade pip &&
      #            pip3 install Cython &&
      #            pip3 install -r requirements.txt
      #    CIBW_BUILD: "cp38-macosx_x86_64"
      #    CIBW_ARCHS_MACOS: "x86_64"
          
      #- name: Show files
      #  run: ls -lh wheelhouse
      #  shell: bash

      #- name: Upload wheels
      #  shell: bash
      #  env:
      #          PYPI_UPLOAD: ${{ secrets.PYPI_UPLOAD }}
      #          PYPI_USR: ${{ secrets.PYPI_USR }}
      #          PYPI_PWD: ${{ secrets.PYPI_PWD }}
      #          TEST_PYPI_USR: ${{ secrets.TEST_PYPI_USR }}
      #          TEST_PYPI_PWD: ${{ secrets.TEST_PYPI_PWD }}
      #  run: |
      #          pip3 install --upgrade pip
      #          pip3 install twine
      #          chmod +x upload_wheels.sh
      #          ./upload_wheels.sh
